# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: BetterTradePotatoes_development

test:
  <<: *default
  database: BetterTradePotatoes_test

production:
  <<: *default
  database: BetterTradePotatoes_production
  username: BetterTradePotatoes
  password: <%= ENV["BETTERTRADEPOTATOES_DATABASE_PASSWORD"] %>
